services:
  version:
    build:
      context: .
      dockerfile: dockerfile.prod
    image: drglasdou/disagro_node:1

  latest:
    build:
      context: .
      dockerfile: dockerfile.prod
    image: drglasdou/disagro_node:latest
